---
# vars file for tpa_scaffolding
tpa_single_node_base_hostname: trustification
tpa_single_node_certificates_dir: certs/
tpa_single_node_config_dir: /etc/rhtpa
tpa_single_node_kube_manifest_dir: "{{ tpa_single_node_config_dir }}/manifests"
tpa_single_node_secrets_dir: "{{ tpa_single_node_config_dir }}/secrets"
tpa_single_node_namespace: trustification
tpa_single_node_podman_network: tcnet
tpa_single_node_systemd_directory: /etc/systemd/system
tpa_single_node_default_empty: ""

# DB_SERVICE
tpa_single_node_pg_host: "{{ lookup('env', 'TPA_PG_HOST') | default('192.168.56.0', true) }}"
tpa_single_node_pg_port: 5432
tpa_single_node_pg_db: guac
tpa_single_node_pg_admin: "{{ lookup('env', 'TPA_PG_ADMIN') }}"
tpa_single_node_pg_admin_passwd: "{{ lookup('env', 'TPA_PG_ADMIN_PASSWORD') }}"
tpa_single_node_pg_user: "{{ lookup('env', 'TPA_PG_USER') }}"
tpa_single_node_pg_user_passwd: "{{ lookup('env', 'TPA_PG_USER_PASSWORD') }}"
tpa_single_node_pg_ssl_mode: disable


# SSO_SERVICE
tpa_single_node_oidc_issuer_url: "{{ lookup('env', 'TPA_OIDC_ISSUER_URL') | default('tpa_single_node_default_empty', true) }}"
tpa_single_node_oidc_frontend_id: "{{ lookup('env', 'TPA_OIDC_FRONTEND_ID') | default('tpa_single_node_default_empty', true) }}"
tpa_single_node_oidc_provider_client_id: "{{ lookup('env', 'TPA_OIDC_PROVIDER_CLIENT_ID') | default('tpa_single_node_default_empty', true) }}"
tpa_single_node_oidc_provider_client_secret: "{{ lookup('env', 'TPA_OIDC_PROVIDER_CLIENT_SECRET') | default('tpa_single_node_default_empty', true) }}"

# TSL Certificates
tpa_single_node_collector_osv_tls_crt_path: "{{ tpa_single_node_certificates_dir }}/collector-osv-tls-certificate.pem"
tpa_single_node_collector_osv_tls_key_path: "{{ tpa_single_node_certificates_dir }}/collector-osv-tls-certificate.key"
tpa_single_node_client_tls_ca_certificate_path: "{{ tpa_single_node_certificates_dir }}/service-ca.crt"
tpa_single_node_spog_api_tls_crt_path: "{{ tpa_single_node_certificates_dir }}/spog-api-tls-certificate.pem"
tpa_single_node_spog_api_tls_key_path: "{{ tpa_single_node_certificates_dir }}/spog-api-tls-certificate.key"

# Target node(s) - Secret and Configmap locations
tpa_single_node_storage_secret: "{{ tpa_single_node_kube_manifest_dir }}/storage-secret.yaml"
tpa_single_node_event_secret: "{{ tpa_single_node_kube_manifest_dir }}/event-secret.yaml"
tpa_single_node_oidc_secret: "{{ tpa_single_node_kube_manifest_dir }}/oidc-secret.yaml"

# ports
tpa_single_node_vexination_api_port: 8081
tpa_single_node_bombastic_api_port: 8082
tpa_single_node_spog_api_port: 8084
tpa_single_node_v11y_api_port: 8087
