services:
  keycloak:
    image: docker.io/bitnami/keycloak:23.0.7
    environment:
      - KEYCLOAK_DATABASE_VENDOR=dev-file
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123456
      - KEYCLOAK_ENABLE_HEALTH_ENDPOINTS=true
      - KEYCLOAK_CACHE_TYPE=local
    ports:
      - "8090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 5s
      timeout: 5s
      retries: 20

  init-keycloak:
    image: docker.io/bitnami/keycloak:23.0.7
    depends_on:
      keycloak:
        condition: service_healthy
      # FIXME: broken in podman: https://github.com/containers/podman-compose/issues/575
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KCADM_PATH=/opt/bitnami/keycloak/bin/kcadm.sh
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123456
      - REALM=trustify
      - INIT_DATA=/init-sso/data
      - CHICKEN_ADMIN=admin
      - CHICKEN_ADMIN_PASSWORD=admin123456
      - REDIRECT_URIS=["http://localhost:*"]
      - WALKER_SECRET=ZVzq9AMOVUdMY1lSohpx1jI3aW56QDPS
      # The internal name (between containers) is "keycloak". However, from the host it reachable as "localhost:8090".
      # So the "frontend" needs to be set to that
      - SSO_FRONTEND_URL=http://localhost:8090
    volumes:
      - ./config/init-sso:/init-sso${SELINUX_VOLUME_OPTIONS}
    entrypoint: /usr/bin/bash
    command: /init-sso/init.sh

  postgres:
    image: docker.io/library/postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres1234"
      POSTGRES_DB: "rhtpa"
    restart: always
    shm_size: "1g"

  minio:
    image: quay.io/minio/minio:RELEASE.2025-02-28T09-55-16Z
    command: server --console-address ":9001" /data1
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 10
    networks:
      default:
        aliases:
          - trustify.minio
          - minio

  createbuckets:
    image: quay.io/minio/mc:RELEASE.2025-02-21T16-00-46Z
    entrypoint:
      - /bin/sh
      - -c
      - |
        /usr/bin/mc config host add myminio http://minio:9000 admin password;
        /usr/bin/mc mb myminio/trustify || true;
        /usr/bin/mc anonymous set public myminio/trustify;
        /usr/bin/mc admin service restart myminio;
