---
- name: Copy create-importers.sql to Server
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.template', 'configs/create-importers.sql') }}"
    dest: "{{ tpa_single_node_config_dir }}/create-importers.sql"
    remote_src: true
    mode: "0600"

- name: Run create-importers.sql
  ansible.builtin.command: "psql postgresql://{{ tpa_single_node_pg_user }}:{{ tpa_single_node_pg_user_passwd }}@\
      {{ tpa_single_node_pg_host }}:{{ tpa_single_node_pg_port }}/{{ tpa_single_node_pg_db }}?sslmode={{ tpa_single_node_pg_ssl_mode }} \
      -v ON_ERROR_STOP=1 \
      -f {{ tpa_single_node_config_dir }}/create-importers.sql"
  changed_when: false
  no_log: false
  register: result
  retries: 2
  delay: 5
  until: result.rc == 0

- name: Deploy importerA
  ansible.builtin.include_tasks: install_manifest.yml
  vars:
    podman_spec:
      state: started
      systemd_file: importerA
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/importer/DeploymentA.yaml.j2') | from_yaml }}"

- name: Deploy importerB
  ansible.builtin.include_tasks: install_manifest.yml
  vars:
    podman_spec:
      state: started
      systemd_file: importerB
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/importer/DeploymentB.yaml.j2') | from_yaml }}"

- name: Deploy importerC
  ansible.builtin.include_tasks: install_manifest.yml
  vars:
    podman_spec:
      state: started
      systemd_file: importerC
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/importer/DeploymentC.yaml.j2') | from_yaml }}"

- name: Deploy importerD
  ansible.builtin.include_tasks: install_manifest.yml
  vars:
    podman_spec:
      state: started
      systemd_file: importerD
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/importer/DeploymentD.yaml.j2') | from_yaml }}"
